# {"time":"2025-03-28T21:31:55.500951602Z","level":"INFO","msg":"Request processed successfully","status_code":"200","response":"Success","sequence_info":{"logger_id":"54b481fa-9059-4435-a45d-330e81560d49","sequence_no":1392}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  labels:
    component: fluentd
data:
  fluent.conf: |
    <source>
      @type forward
      port 24224
      bind 0.0.0.0
      tag app.logs
    </source>

    <match app.logs>
      @type rewrite_tag_filter
      <rule>
        key hostname
        pattern /(.*)/
        tag ${tag}.$1
      </rule>
    </match>

    <match app.logs.*>
      @type copy
      <store>
        @type elasticsearch
        host elasticsearch.elastic.svc.cluster.local
        port 9200
        logstash_format true
        logstash_prefix fluentd
        flush_interval 1s
      </store>

      <store>
        @type file
        path /var/log/fluentd/go-app/${tag}/glidein.log
        compress gzip
        append true
        <buffer tag>
          path /var/log/fluentd/buf/
          timekey 5m
          timekey_use_utc true
          timekey_wait 2m
        </buffer>
      </store>
    </match>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fluentd
  labels:
    component: fluentd
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: fluentd
  replicas: 1
  template:
    metadata:
      labels:
        component: fluentd
    spec:
      containers:
        - name: fluentd
          image: hub.opensciencegrid.org/mwestphall/fluentd
          resources:
            requests:
              memory: 500Mi
              cpu: '0.5'
            limits:
              memory: 1Gi
              cpu: '2'
          volumeMounts:
            - name: fluentd-config
              mountPath: /fluentd/etc
            - name: log-storage
              mountPath: /var/log/fluentd/
      volumes:
        - name: fluentd-config
          configMap:
            name: fluentd-config
        - name: log-storage
          emptyDir:
            sizeLimit: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: fluentd
  labels:
    component: fluentd
spec:
  ports:
  - port: 24224
  selector:
    component: fluentd
